### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [xh4vm/graduate_work#13]
Привет! Молодцы! Здорово, что развернулись на публичном адресе) У меня всего несколько рекомендаций:

1. [Это](https://github.com/xh4vm/graduate_work/blob/dbf953d8cc9549c6ecc6c8b47578f37e625b5ae2/docker-compose.yml#L701) стоит вынести в `entrypoint_airflow.sh`, чтобы не перегружать ваш и так большой docker-compose
2. [Тут](https://github.com/xh4vm/graduate_work/blob/dbf953d8cc9549c6ecc6c8b47578f37e625b5ae2/nginx/configs/producer_storage.conf#L30) что-то наворотили с location'ми. Еще раз рекомендую ознакомиться с докой о try_files: http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files. Разобраться где вам нужна обработка статики и только там его использовать
3. А зачем [здесь](https://github.com/xh4vm/graduate_work/blob/main/recommender_system/docker-compose.yml) почти полная копия docker-compose из корня репозитория?
4. [Тут](https://github.com/xh4vm/graduate_work/blob/dbf953d8cc9549c6ecc6c8b47578f37e625b5ae2/recommender_system/airflow/src/models/movie.py#L34) странный дефолт, по идее лучше сделать это поле обязательным, иначе со случайной продолжительностью фильма, если ее не указали - вы будете вносить "шум" в вашу метрику
5. [Это](https://github.com/xh4vm/graduate_work/blob/dbf953d8cc9549c6ecc6c8b47578f37e625b5ae2/recommender_system/airflow/src/load/base.py#L7) устаревший декоратор: https://docs.python.org/3/library/abc.html#abc.abstractproperty
6. Можно лучше: [тут](https://github.com/xh4vm/graduate_work/blob/dbf953d8cc9549c6ecc6c8b47578f37e625b5ae2/recommender_system/airflow/src/load/mongo.py#L18) немного странная архитектура: вы передаете внутрь инстанс AsyncIOMotorClient, но при этом в других методах позволяете пересоздавать объект, но при этом не самому классу, а через внешние методы. Обычно так не делают, а делают один из двух вариантов: класс-обертка, которая вообще ничего не делает с подключением, кроме навешивания интерфейса, либо вы наоборот прячете за классом всю кухню с AsyncIOMotorClient и даете в наружу только методы для работы с данными.
7. Очень странно, когда [метод](https://github.com/xh4vm/graduate_work/blob/dbf953d8cc9549c6ecc6c8b47578f37e625b5ae2/recommender_system/airflow/src/extract/metadata/csv.py#L21) сначала возвратит список заголовков, а потом начнет словари генерить. Лучше бы получение заголовков сделать отдельным методом. И вы можете упростить код, если возьмете: https://docs.python.org/3/library/csv.html#csv.DictReader
8. Мы постоянно дорабатываем документацию, но момент с [aioredis](https://github.com/xh4vm/graduate_work/blob/dbf953d8cc9549c6ecc6c8b47578f37e625b5ae2/recommender_system/grpc/requirements.txt#L1) еще не заменили. В общем, он еще с февраля прошлого года переехал в redis-py и в основном репо код не обновляется. Подробнее в readme: https://github.com/aio-libs/aioredis-py
9. В асинхронном [методе](https://github.com/xh4vm/graduate_work/blob/dbf953d8cc9549c6ecc6c8b47578f37e625b5ae2/recommender_system/grpc/services/cache/redis.py#L36) дергаете синхронный ping. Плюс довольно затратно на каждое обращение к кэшу делать такую проверку. Тут стоит использовать концепцию backoff, причем backoff декоратор можно навесить на методы set и get, тогда в случае отвала коннекта он под капотом сам переподключится, можете поизучать код клиента: https://github.com/redis/redis-py/blob/master/redis/asyncio/client.py

**Comment by xh4vm** [comment]
Привет! Спасибо за ревью ☺️
Единственное, я не очень понял, что ты имеешь в виду по пункту 6

Если я сделаю класс отвечающий только за подключение, типо:

```
class BaseClient(ABC):
    @property
    @abstractmethod
    def conn(self):
        pass

class AsyncMongoClient(BaseClient):
      ...
    @property
    @backoff.on_exception(**BACKOFF_CONFIG, logger=logger)
    def conn(self) -> AsyncIOMotorClient:
        pass
       ...
```

А в сам лоадер передам интерфейс подключения

```
class AsyncMongoLoader(BaseLoader):
    def __init__(self, settings: DBSettings, client: BaseClient):
        self._settings: DBSettings = settings
        self.client: BaseClient = client
    
    async def load(
        self,
        db_name: str,
        collection_name: str,
        data: Iterator[ModelMetaclass]
    ) -> List[Any]:
        pass
```

Тогда по идее я уйду от указанных выше проблем?

**Comment by BigDeepBlue** [comment]
> Тогда по идее я уйду от указанных выше проблем?

ага, например так

**Comment by BigDeepBlue** [comment]
Принято! Удачи на защите :rocket:
